In [1]:
import pandas as pd
df = pd.read_csv('data/old/hh_skills_rpa_аналитик_113.csv', delimiter=',')
df.head(30)

                                   Навык  Количество Процент
0                                    SQL           7   6.31%
1         Разработка технических заданий           4   3.60%
2                                 Python           4   3.60%
3                 Аналитическое мышление           3   2.70%
4                Анализ бизнес-процессов           3   2.70%
5         Постановка задач разработчикам           2   1.80%
6                                  Agile           2   1.80%
7                      Анализ требований           2   1.80%
8              Описание бизнес-процессов           2   1.80%
9                               Power BI           2   1.80%
10        Автоматизация бизнес-процессов           2   1.80%
11                            PostgreSQL           2   1.80%
12                                   RPA           2   1.80%
13                           B2B Продажи           2   1.80%
14                      Системный анализ           2   1.80%
15                              Use case           1   0.90%
16  Разработка функциональных требований           1   0.90%
17               Управление требованиями           1   0.90%
18                             A/A тесты           1   0.90%
19                               CustDev           1   0.90%
20                            User Story           1   0.90%
21                                   MVP           1   0.90%
22                         Бизнес-анализ           1   0.90%
23                         Анализ данных           1   0.90%
24                   Продуктовые метрики           1   0.90%
25                                  Java           1   0.90%
26                     1С: Предприятие 8           1   0.90%
27          Оптимизация бизнес-процессов           1   0.90%
28               Автоматизация процессов           1   0.90%
29                            1С-Битрикс           1   0.90%

In [2]:
df = pd.read_csv('data/old/hh_skills_бизнес_аналитик_113.csv', delimiter=',')
df.head(30)

                                  Навык  Количество Процент
0                         Бизнес-анализ         165   6.24%
1                Аналитическое мышление          99   3.74%
2                                  BPMN          96   3.63%
3                                   SQL          89   3.37%
4               Анализ бизнес-процессов          76   2.87%
5                      Системный анализ          56   2.12%
6                              MS Excel          55   2.08%
7          Оптимизация бизнес-процессов          55   2.08%
8        Разработка технических заданий          50   1.89%
9        Постановка задач разработчикам          49   1.85%
10            Описание бизнес-процессов          46   1.74%
11                                  UML          41   1.55%
12       Моделирование бизнес-процессов          39   1.48%
13       Автоматизация бизнес-процессов          39   1.48%
14                        Анализ данных          31   1.17%
15                             Power BI          30   1.13%
16       Моделирование бизнес процессов          27   1.02%
17  Работа с большим объемом информации          24   0.91%
18         Разработка бизнес-требований          23   0.87%
19                        MS PowerPoint          23   0.87%
20                               Python          22   0.83%
21                    Анализ требований          22   0.83%
22                                  CRM          22   0.83%
23                            Аналитика          19   0.72%
24                           User Story          19   0.72%
25                            Битрикс24          18   0.68%
26                 Управление проектами          17   0.64%
27          Стратегическое планирование          17   0.64%
28         Управление бизнес процессами          16   0.61%
29                 Atlassian Confluence          16   0.61%

In [3]:
df = pd.read_csv('data/old/hh_skills_менеджер_проекта_113.csv', delimiter=',')
df.head(30)

                                  Навык  Количество Процент
0                  Деловая коммуникация         114   3.79%
1                     Деловая переписка          99   3.29%
2                  Управление проектами          89   2.96%
3                Организаторские навыки          87   2.89%
4                       Деловое общение          58   1.93%
5                   Ведение переговоров          53   1.76%
6                  Заключение договоров          52   1.73%
7                      Работа в команде          51   1.70%
8                  Проектный менеджмент          43   1.43%
9                 Телефонные переговоры          37   1.23%
10  Работа с большим объемом информации          37   1.23%
11                   Project management          30   1.00%
12                 Планирование бюджета          26   0.86%
13            Управление коммуникациями          26   0.86%
14                  Управление командой          26   0.86%
15          Основы управления проектами          25   0.83%
16       Ведение проектной документации          24   0.80%
17                      Английский язык          24   0.80%
18               Жизненный цикл проекта          24   0.80%
19       Разработка технических заданий          23   0.76%
20                          B2B Продажи          22   0.73%
21               Проектная документация          21   0.70%
22                        MS PowerPoint          20   0.67%
23                           MS Project          20   0.67%
24                      Документооборот          19   0.63%
25                             MS Excel          19   0.63%
26                       Грамотная речь          19   0.63%
27                     Активные продажи          19   0.63%
28                   Управление рисками          19   0.63%
29                              AutoCAD          18   0.60%

In [4]:
df = pd.read_csv('data/old/hh_skills_руководитель_проекта_113.csv', delimiter=',')
df.head(30)

                             Навык  Количество Процент
0             Управление проектами         107   3.92%
1           Организаторские навыки          99   3.63%
2             Деловая коммуникация          88   3.22%
3                Деловая переписка          64   2.34%
4           Проектная документация          50   1.83%
5              Ведение переговоров          48   1.76%
6                    Строительство          42   1.54%
7                       MS Project          40   1.47%
8              Управление командой          40   1.47%
9                 Работа в команде          37   1.36%
10            Проектный менеджмент          36   1.32%
11     Основы управления проектами          35   1.28%
12            Планирование бюджета          33   1.21%
13                 Деловое общение          32   1.17%
14            Заключение договоров          30   1.10%
15              Управление рисками          29   1.06%
16         Руководство коллективом          29   1.06%
17            Управление ресурсами          29   1.06%
18                         AutoCAD          29   1.06%
19          Жизненный цикл проекта          29   1.06%
20       Управление коммуникациями          26   0.95%
21                 Английский язык          24   0.88%
22              Project management          24   0.88%
23  Разработка технических заданий          20   0.73%
24                           Scrum          19   0.70%
25                     B2B Продажи          18   0.66%
26     Сопровождение строительства          18   0.66%
27         Управление подрядчиками          18   0.66%
28                 Документооборот          17   0.62%
29       Управление строительством          17   0.62%

In [5]:
df = pd.read_csv('data/old/hh_skills_системный_аналитик_113.csv', delimiter=',')
df.head(30)

                                  Навык  Количество Процент
0                                   SQL         182   6.00%
1                      Системный анализ         180   5.94%
2                                  BPMN         161   5.31%
3                                   UML         141   4.65%
4                         Бизнес-анализ          82   2.70%
5        Постановка задач разработчикам          76   2.51%
6        Разработка технических заданий          63   2.08%
7                                  REST          58   1.91%
8                                  SOAP          55   1.81%
9                                   API          54   1.78%
10               Аналитическое мышление          53   1.75%
11                                  XML          48   1.58%
12                             REST API          42   1.39%
13                                 JSON          41   1.35%
14                       Atlassian Jira          36   1.19%
15                           PostgreSQL          35   1.15%
16                           User Story          33   1.09%
17                 Atlassian Confluence          29   0.96%
18                    Анализ требований          29   0.96%
19                             Use case          24   0.79%
20                 Системная интеграция          24   0.79%
21                         Apache Kafka          24   0.79%
22                                Scrum          23   0.76%
23  Работа с большим объемом информации          22   0.73%
24                                Agile          22   0.73%
25                               MS SQL          22   0.73%
26                               Python          21   0.69%
27       Моделирование бизнес процессов          21   0.69%
28                             JSON API          20   0.66%
29                            Аналитика          19   0.63%

In [6]:
df = pd.read_csv('data/old/hh_skills_финансовый_аналитик_113.csv', delimiter=',')
df.head(30)

                                    Навык  Количество Процент
0                       Финансовый анализ         329   8.17%
1                   Финансовая отчетность         166   4.12%
2                          Бюджетирование         147   3.65%
3                     Финансовый контроль         136   3.38%
4                 Финансовое планирование         126   3.13%
5               Управленческая отчетность         119   2.96%
6                                MS Excel         106   2.63%
7                    Экономический анализ          88   2.19%
8                   Финансовый менеджмент          86   2.14%
9                  Аналитическое мышление          85   2.11%
10  Формирование аналитической отчетности          76   1.89%
11                  Финансовые показатели          71   1.76%
12               Финансовое моделирование          71   1.76%
13          Анализ финансовых показателей          60   1.49%
14    Работа с большим объемом информации          59   1.47%
15                   Планирование бюджета          59   1.47%
16                       План-факт анализ          46   1.14%
17                   Финансовая стратегия          45   1.12%
18                       Финансовый аудит          45   1.12%
19                    Управленческий учет          44   1.09%
20         Отчет о финансовых результатах          44   1.09%
21                       Контроль бюджета          36   0.89%
22                    Планирование затрат          32   0.79%
23  Анализ текущих финансовых показателей          31   0.77%
24        Управление денежными средствами          30   0.75%
25                     Оптимизация затрат          29   0.72%
26      Отчет о движении денежных средств          29   0.72%
27         Основы финансового менеджмента          27   0.67%
28               Бухгалтерская отчетность          27   0.67%
29                          MS PowerPoint          26   0.65%